# Generated by Django 4.2 on 2023-06-06 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=100)),
                ('mavzu', models.CharField(blank=True, max_length=30, null=True)),
                ('sana', models.DateField()),
                ('matn', models.TextField()),
                ('muallif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userapp.foydalanuvchi')),
            ],
        ),
    ]
